// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxak4sLOYgQWFzebVwLspTw57sWOpOBck',
    appId: '1:128659314975:web:217fd04b0760809a1ef82a',
    messagingSenderId: '128659314975',
    projectId: 'fasum-423a9',
    authDomain: 'fasum-423a9.firebaseapp.com',
    storageBucket: 'fasum-423a9.appspot.com',
    measurementId: 'G-EWCXCNDWWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBechaAfcFTvjR3EXm2iRGjLZEeVwbxjiA',
    appId: '1:128659314975:android:884f3b7edce0f93d1ef82a',
    messagingSenderId: '128659314975',
    projectId: 'fasum-423a9',
    storageBucket: 'fasum-423a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmZoYoocBsFXOlqHJMTGom6S-MYfQ_ES4',
    appId: '1:128659314975:ios:ff5ef6991e783c361ef82a',
    messagingSenderId: '128659314975',
    projectId: 'fasum-423a9',
    storageBucket: 'fasum-423a9.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmZoYoocBsFXOlqHJMTGom6S-MYfQ_ES4',
    appId: '1:128659314975:ios:970e1b13daa71cc31ef82a',
    messagingSenderId: '128659314975',
    projectId: 'fasum-423a9',
    storageBucket: 'fasum-423a9.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
